[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lottery = "13r5dniDEeMszUj4kMyQHcpQEKQmvDWYwjevdkB4Ta9"
staking = "3K44q3YYWGyeXsW3sh5zM1QkfDNiPjuSKPJko5v28WPo"

[programs.localnet]
lottery = "13r5dniDEeMszUj4kMyQHcpQEKQmvDWYwjevdkB4Ta9"
staking = "3K44q3YYWGyeXsW3sh5zM1QkfDNiPjuSKPJko5v28WPo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./common_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
