[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lottery = "6q1FDc6PWjEzaVgjjHbDvzrYtbiKYTgS6Bwpc7LABweV"
staking = "HRij1YGqCYPpPUbEVPpH4qQPJb3gfZosHKuKydDYGqzT"

[programs.localnet]
alyra_staking2 = "DQ2xiRbRvJuymAZSTj7kd7T8Auagh49NuKv6jS8kpX5c"
so_pool = "J6mPMTYtKxVzxH8EZk5GmjueJd2uXUmymY4eUdXLkFQX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./common_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
