[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lottery = "2JfVxGG5w5nxPwHKzMdhoewAhxz5Gj9wBKyZSuzQQ4Ye"
staking = "2X9yDvzea1rfp7NyRn9Fwi9ikhh2ho84pvDJ34GQSvWb"

[programs.localnet]
so_pool = "J6mPMTYtKxVzxH8EZk5GmjueJd2uXUmymY4eUdXLkFQX"
staking = "2X9yDvzea1rfp7NyRn9Fwi9ikhh2ho84pvDJ34GQSvWb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./common_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
